server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bootcamp-customer-service
          uri: lb://BOOTCAMP-CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: bootcamp-product-service
          uri: lb://BOOTCAMP-PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: bootcamp-bankaccount-service
          uri: lb://BOOTCAMP-BANKACCOUNT-SERVICE
          predicates:
            - Path=/api/bankAccount/**
        - id: bootcamp-credit-service
          uri: lb://BOOTCAMP-CREDIT-SERVICE
          predicates:
            - Path=/api/credit/**
        - id: bootcamp-customertype-service
          uri: lb://BOOTCAMP-CUSTOMERTYPE-SERVICE
          predicates:
            - Path=/api/customerType/**
        - id: bootcamp-payment-service
          uri: lb://BOOTCAMP-PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

#circuitBraker
resilience4j:
  circuitbreaker:
    instances:
      customerTypeInfoService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        #timeoutDuration: 2s
      productInfoService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        #timeoutDuration: 2s

#actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always