#port
server:
  port: 8081

#mongodb
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.oksp7.mongodb.net/bootcamp_customer?retryWrites=true&w=majority

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

