#port
server:
  port: 8087

#mongodb
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.oksp7.mongodb.net/bootcamp-product?retryWrites=true&w=majority

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/